language: python
python: "2.7"
install:
  - rm -r /home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/setuptools*
  - rm -r /home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/distribute*
  - wget http://downloads.buildout.org/2/bootstrap.py
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bin/test